name: AndroidBuild

on:
  pull_request:
    branches:
      - main
      - develop

  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          api-level: 30
          components: build-tools;30.0.3

      - name: Grant execute permission for gradlew
        run: chmod +x ./frontend/gradlew

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-${{ runner.os }}

      - name: Build with Gradle
        run: ./frontend/gradlew build

      - name: Assemble Project
        run: ./frontend/gradlew assemble

      - name: Start Emulator
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils
          sudo adduser $USER libvirt
          sudo adduser $USER kvm
          avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64"
          $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio -no-boot-anim -gpu off &

      - name: Wait for Emulator
        run: |
          adb wait-for-device
          adb shell input keyevent 82

      - name: Run Espresso Tests
        run: ./frontend/gradlew connectedAndroidTest

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Smart-Storage-Organizer-Application.apk
          path: frontend/app/build/outputs/apk/debug/*.apk
