name: AndroidBuild

on:
  pull_request:
    branches:
      - main
      - develop

  push:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: 11
          distribution: 'adopt'
          
      - name: Build Project
        run: ./gradlew assemble
        working-directory: frontend

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Smart-Storage-Organizer-Application.apk
          path: app/build/outputs/apk/debug/*.apk
