name: Smart Storage Organizer CI/CD

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Gradle
      run:  cd frontend && ./gradlew build

    - name: Run Tests
      run:  cd frontend && ./gradlew test

    - name: Run Espresso Tests
      run:  cd frontend && ./gradlew connectedAndroidTest
