name: Smart Storage Organizer CI/CD

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        node-version: '20'

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        node-version: '20'
        distribution: 'adopt'
        java-version: '17'

    - name: Build with Gradle
      run: |
        cd frontend
        ./gradlew build

    - name: Run Tests
      run: |
        cd frontend
        ./gradlew test

    - name: Run Espresso Tests
      working-directory: frontend
      run: ./gradlew connectedAndroidTest
